
- repo: git://github.com/dnephin/pre-commit-golang
  sha: HEAD
  
  hooks:
    -   id: go-fmt
        exclude: ^vendor/
    -   id: go-vet
        exclude: ^vendor/
    -   id: go-lint
        exclude: ^vendor/
         